# -*- coding: utf-8 -*-
"""markup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cdci7Wy-7TyG_P8E1IAwIWk-GPTomGwf
"""

select ord_id,ord_datetime,ord_an,round(((an_price - an_cost)::numeric/an_cost)*100,3) as markup from analysis as a 
join orders as o on
a.an_id = o.ord_an